import 'package:get/get.dart';

class LocalLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'next': 'Next',
          'farmerlogin': 'Farmer Login',
          'expertlogin': 'Expert Login',
          'google': 'Login with Google',
          'signout': 'SignOut',
          'name': 'Name',
          'state': 'State',
          'district': 'District',
          'taluka': 'Taluka',
          'village': 'Village',
          'pincode': 'Pincode',
          'submit': 'Submit',
          'pen': 'please enter name',
          'ped': 'please enter district',
          'pes': 'please enter state',
          'pet': 'please enter taluka',
          'pev': 'please enter village',
          'pep': 'please enter pincode',
          'myproblem': 'My Problem',
          'mysolution': 'My Solution',
          'help': 'Help',
          'pevd': 'please enter valid code',
          'og': 'Open Gallery',
          'oc': 'Open Camera',
          'up': 'Upload Photo',
          'uv': 'Upload Video',
          'cn': 'Crop Name',
          'wap': 'Write a problem',
          'Select State': 'Select State',
          'Andaman and Nicobar Islands': 'Andaman and Nicobar Islands',
          'Andhra Pradesh': 'Andhra Pradesh',
          'Arunachal Pradesh': 'Arunachal Pradesh',
          'Assam': 'Assam',
          'Bihar': 'Bihar',
          'Chandigarh': 'Chandigarh',
          'Chhattisgarh': 'Chhattisgarh',
          'Dadra and Nagar Haveli and Daman and Diu':
          'Dadra and Nagar Haveli and Daman and Diu',
          'Delhi': 'Delhi',
          'Goa': 'Goa',
          'Gujarat': 'Gujarat',
          'Haryana': 'Haryana',
          'Himachal Pradesh': 'Himachal Pradesh',
          'Jammu and Kashmir': 'Jammu and Kashmir',
          'Jharkhand': 'Jharkhand',
          'Karnataka': 'Karnataka',
          'Kerala': 'Kerala',
          'Ladakh': 'Ladakh',
          'Lakshadweep': 'Lakshadweep',
          'Madhya Pradesh': 'Madhya Pradesh',
          'Maharashtra': 'Maharashtra',
          'Manipur': 'Manipur',
          'Meghalaya': 'Meghalaya',
          'Mizoram': 'Mizoram',
          'Nagaland': 'Nagaland',
          'Odisha': 'Odisha',
          'Puducherry': 'Puducherry',
          'Punjab': 'Punjab',
          'Rajasthan': 'Rajasthan',
          'Sikkim': 'Sikkim',
          'Tamil Nadu': 'Tamil Nadu',
          'Telangana': 'Telangana',
          'Tripura': 'Tripura',
          'Uttar Pradesh': 'Uttar Pradesh',
          'Uttarakhand': 'Uttarakhand',
          'West Bengal': 'West Bengal',
          'problem' : 'Problems Pending',
          'solution': 'Problem Solved',


        },
        'hi_IN': {
          'next': 'अगला',
          'farmerlogin': 'किसान लॉगिन',
          'expertlogin': 'विशेषज्ञ लॉगिन',
          'google': 'गूगल से लॉगिन करें',
          'signout': 'साइन आउट',
          'name': 'नाम',
          'state': 'राज्य',
          'district': 'ज़िला',
          'taluka': 'तालुका',
          'village': 'गाँव',
          'pincode': 'पिन कोड',
          'submit': 'जमा करना',
          'pen': 'कृपया नाम दर्ज करें',
          'ped': 'कृपया जिला दर्ज करें',
          'pes': 'कृपया राज्य दर्ज करें',
          'pet': 'कृपया तालुका नाम दर्ज करें',
          'pev': 'कृपया गांव का नाम दर्ज करें',
          'pep': 'कृपया पिनकोड दर्ज करें',
          'myproblem': 'मेरी समस्या',
          'mysolution': 'मेरा समाधान',
          'help': 'मदद',
          'pevd': 'कृपया वैध कोड दर्ज करें',
          'og': 'ओपन गैलरी',
          'oc': 'कैमरा खोलो',
          'up': 'फोटो अपलोड करें',
          'uv': 'विडियो को अॅॅपलोड करें',
          'cn': 'फसल का नाम',
          'wap': 'समस्या लिखें',
          'Select State': 'राज्य चुनें',
          'Andaman and Nicobar Islands': 'अंडमान व नोकोबार द्वीप समूह',
          'Andhra Pradesh': 'आंध्र प्रदेश',
          'Arunachal Pradesh': 'अरुणाचल प्रदेश',
          'Assam': 'असम',
          'Bihar': 'बिहार',
          'Chandigarh': 'चंडीगढ़',
          'Chhattisgarh': 'छत्तीसगढ़',
          'Dadra and Nagar Haveli and Daman and Diu':
          'दादरा और नगर हवेली और दमन और दीव',
          'Delhi': 'दिल्ली',
          'Goa': 'गोवा',
          'Gujarat': 'गुजरात',
          'Haryana': 'गुजरात',
          'Himachal Pradesh': 'हिमाचल प्रदेश',
          'Jammu and Kashmir': 'जम्मू और कश्मीर',
          'Jharkhand': 'झारखंड',
          'Karnataka': 'कर्नाटक',
          'Kerala': 'केरल',
          'Ladakh': 'लद्दाख',
          'Lakshadweep': 'लक्षद्वीप ',
          'Madhya Pradesh': 'मध्य प्रदेश',
          'Maharashtra': 'महाराष्ट्र',
          'Manipur': 'मणिपुर',
          'Meghalaya': 'मेघालय',
          'Mizoram': 'मिजोरम',
          'Nagaland': 'नागालैंड',
          'Odisha': 'ओडिशा',
          'Puducherry': 'पुडुचेरी',
          'Punjab': 'पंजाब',
          'Rajasthan': 'राजस्थान',
          'Sikkim': 'सिक्किम',
          'Tamil Nadu': 'तमिलनाडु',
          'Telangana': 'तेलंगाना',
          'Tripura': 'त्रिपुरा',
          'Uttar Pradesh': 'उतार प्रदेश',
          'Uttarakhand': 'उत्तराखंड',
          'West Bengal': 'पश्चिम बंगाल',
        },

        
        'mr_IN': {
          'next': 'पुढे',
          'farmerlogin': 'शेतकरी लॉगिन',
          'expertlogin': 'तज्ञ लॉगिन',
          'google': 'Google सह लॉगिन करा',
          'signout': 'साइनआउट',
          'name': 'नाव',
          'state': 'राज्य',
          'district': 'जिल्हा',
          'taluka': 'तालुका',
          'village': 'गाव',
          'pincode': 'पिन कोड',
          'submit': 'प्रस्तुत करणे',
          'pen': 'कृपया नाव प्रविष्ट करा',
          'ped': 'कृपया जिल्ह्याचे नाव प्रविष्ट करा',
          'pes': 'कृपया राज्याचे नाव प्रविष्ट करा',
          'pet': 'कृपया तालुक्याचे नाव टाका',
          'pev': 'कृपया गावाचे नाव टाका',
          'pep': 'कृपया पिनकोड टाका',
          'myproblem': 'माझी समस्या',
          'mysolution': 'माझे समाधान',
          'help': 'मदत',
          'pevd': 'कृपया वैध कोड प्रविष्ट करा',
          'og': 'ओपन गॅलरी',
          'oc': 'ओपन कॅमेरा',
          'up': 'फोटो अपलोड करा',
          'uv': 'व्हिडिओ अपलोड करा',
          'cn': 'पिकाचे नाव',
          'wap': 'समस्या लिहा',
          'Select State': 'राज्य निवडा',
          'Andaman and Nicobar Islands': 'अंडमान व नोकोबार द्वीप समूह',
          'Andhra Pradesh': 'आंध्र प्रदेश',
          'Arunachal Pradesh': 'अरुणाचल प्रदेश',
          'Assam': 'असम',
          'Bihar': 'बिहार',
          'Chandigarh': 'चंडीगढ़',
          'Chhattisgarh': 'छत्तीसगढ़',
          'Dadra and Nagar Haveli and Daman and Diu':
          'दादरा और नगर हवेली और दमन और दीव',
          'Delhi': 'दिल्ली',
          'Goa': 'गोवा',
          'Gujarat': 'गुजरात',
          'Haryana': 'गुजरात',
          'Himachal Pradesh': 'हिमाचल प्रदेश',
          'Jammu and Kashmir': 'जम्मू और कश्मीर',
          'Jharkhand': 'झारखंड',
          'Karnataka': 'कर्नाटक',
          'Kerala': 'केरल',
          'Ladakh': 'लद्दाख',
          'Lakshadweep': 'लक्षद्वीप',
          'Madhya Pradesh': 'मध्य प्रदेश',
          'Maharashtra': 'महाराष्ट्र',
          'Manipur': 'मणिपुर',
          'Meghalaya': 'मेघालय',
          'Mizoram': 'मिजोरम',
          'Nagaland': 'नागालैंड',
          'Odisha': 'ओडिशा',
          'Puducherry': 'पुडुचेरी',
          'Punjab': 'पंजाब',
          'Rajasthan': 'राजस्थान',
          'Sikkim': 'सिक्किम',
          'Tamil Nadu': 'तमिलनाडु',
          'Telangana': 'तेलंगाना',
          'Tripura': 'त्रिपुरा',
          'Uttar Pradesh': 'उतार प्रदेश',
          'Uttarakhand': 'उत्तराखंड',
          'West Bengal': 'पश्चिम बंगाल',
        }
      };
}
